name: flutter_integration_material_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  shared_preferences: ^2.0.11
  http: ^0.13.4
  giffy_dialog: ^1.8.0
  cupertino_icons: ^1.0.3
  provider: ^6.0.1
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_pdfview: ^1.2.1
  path_provider: ^2.0.8
  file_picker: ^4.3.3
  signature: ^5.0.0
  permission_handler: ^9.1.0
  another_flushbar: ^1.10.28
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family : Heart
      fonts:
        - asset: assets/font/HaveHeartOne.ttf
          weight: 500
    - family : Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400
    - family : Berlin
      fonts:
        - asset: assets/font/berlin.TTF
          weight: 600
    - family: Popins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
    - family : Amira
      fonts:
        - asset: assets/font/Amira.otf
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight: 600
    - family : Sofia
      fonts:
        - asset: assets/font/Sofia/SofiaProBold.otf
          weight: 900
        - asset: assets/font/Sofia/SofiaProSemiBold.otf
          weight: 800
        - asset: assets/font/Sofia/SofiaProMedium.otf
          weight: 700
        - asset: assets/font/Sofia/SofiaProRegular.otf
          weight: 600
        - asset: assets/font/Sofia/SofiaProLight.otf
          weight: 500
        - asset: assets/font/Sofia/SofiaProExtraLight.otf
          weight: 400
        - asset: assets/font/Sofia/SofiaProUltraLight.otf
          weight: 300

  # To addlib/Screen/UI_Screen/Plane_Apps/Assets to your application, add anlib/Screen/UI_Screen/Plane_Apps/Assets section, like this:
  assets:
    - assets/images/SplashScreen.png
    - assets/pdf/sample.pdf
    - assets/integration/language_integration/
    - lib/Screen/Integration/Language_Integration/language/ar-DZ.json
    - lib/Screen/Integration/Language_Integration/language/en-US.json
    - lib/Screen/Integration/Language_Integration/language/zh-CN.json
    - lib/Screen/Integration/Language_Integration/language/pt-BR.json
    - lib/Screen/Integration/Language_Integration/language/hi-IN.json
    - lib/Screen/Integration/Language_Integration/language/id-ID.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
